#!/usr/bin/env php
<?php
require_once('lib/CS495Group2/G2GA1/G2GA1Cipher.php');

use CS495Group2\G2GA1\G2GA1Cipher;


/* Verify arguments and start cipher
============================================================================= */

if ($argc != 6) {
    if ($argc == 1 || in_array(
        $argv[1],
        array('--help', '-help', '-h', '-?'))) {
        showUsage();
    } else {
        showUsageErr('Six arguments are required.');
    }
} else {
    // Hide CLI arguments (including keys) from process title
    setTitle('g2ga1');

    // Perform quick sanity check on args
    verifyArgs($argv);

    // Run cipher
    startCipher($argv);
}


/* Main g2ga1 functions
============================================================================= */

function startCipher($argv)
{
    //ini_set('memory_limit', '260M');
    ini_set('memory_limit', '-1');

    // Store text file contents in string
    $text = sanitize(file_get_contents($argv[1]));

    // Store k1 key file contents in string
    $k1 = sanitize(file_get_contents($argv[2]));

    // Set k2 key
    $k2 = hexdec($argv[3]);

    // Set k3 key
    $k3 = sanitize($argv[4]);

    // Set cipher mode
    $mode = sanitize($argv[5]);

    // Encrypt/decrypt based on mode
    if ($mode == 'E') {
        encrypt($text, $k1, $k2, $k3);
    } else {
        decrypt($text, $k1, $k2, $k3);
    }

    echo 'Peak mem usage: ' . memory_get_peak_usage() . PHP_EOL;
}

function encrypt(&$plainText, &$k1, $k2, $k3)
{
    setTitle('g2ga1 - encrypting');

    $g2ga1 = new G2GA1Cipher();

    $start = microtime(true);
    echo 'Encryption start'. PHP_EOL;
    $cipherText = $g2ga1->encrypt($plainText, $k1, $k2, $k3);
    $stop = microtime(true);
    echo 'Encryption done after (s): ' . ($stop - $start) . PHP_EOL;

    // Output ciphertext
    //echo $cipherText . PHP_EOL;

    $encMessageHandle = fopen('encMessage.txt', 'w');
    fwrite($encMessageHandle, $cipherText);
    fclose($encMessageHandle);


}

function decrypt(&$cipherText, &$k1, $k2, $k3)
{
    setTitle('g2ga1 - decrypting');

    $g2ga1 = new G2GA1Cipher();

    $start = microtime(true);
    echo 'Decryption start'. PHP_EOL;
    $plainText = $g2ga1->decrypt($cipherText, $k1, $k2, $k3);
    //echo $plainText . PHP_EOL;
    $stop = microtime(true);
    echo 'Decryption done after (s): ' . ($stop - $start) . PHP_EOL;

    // Output plaintext
    //echo $plainText . PHP_EOL;

    $decMessageHandle = fopen('decMessage.txt', 'w');
    fwrite($decMessageHandle, $plainText);
    fclose($decMessageHandle); 
}


/* Utility functions
============================================================================= */

function showUsage()
{
    printDesc();
?>
Usage: g2ga1 <message_file> <k1_file> <k2> <k3> <mode>

  <message_file>   The text file to be encrypted/decrypted.
  <k1_file>        The text file that contains the k1 key.
  <k2>             A numerical (base 16) value for the k2 key.
  <k3>             A string containing the letters for the k3 key.
  <mode>           Either 'E' for encryption, or 'D' for decryption.

Examples:
 To encrypt:
  g2ga1 /path/to/message /path/to/k1 C015 K3SECRET E

 To decrypt:
  g2ga1 /path/to/message /path/to/k1 C015 K3SECRET D

<?php
}

function showUsageErr($error)
{
    showUsage();
    die('Error: ' . $error . PHP_EOL);
}

function printDesc()
{
?>

CS 495 - Introduction to Cryptography
Group 2 - Group Assignment 1
G2GA1 Cipher Implementation

<?php
}

function setTitle($title)
{
    $version = explode('.', phpversion());

    // if PHP version is >= 5.5 then attempt to set process title
    if ($version[0] >= 5 && $version[1] >= 5) {
        cli_set_process_title($title);
    }
}

function verifyArgs($argv)
{
    // Verify text files exits
    if (!file_exists($argv[1]))
        showUsageErr('File ' . $argv[1] . ' does not exist.');

    // Verify k1 files exits
    if (!file_exists($argv[2]))
        showUsageErr('File ' . $argv[2] . ' does not exist.');

    // Verify k2 is valid hexadecimal value > 0   
    if (hexdec($argv[3]) < 1 || preg_match('/[^A-Fa-f0-9]/', $argv[3]))
        showUsageErr('k2 must be a hexadeciaml value greater than 0.');

    // Verify k3's length > 0, prevents empty string
    if (!(strlen($argv[4]) > 0))
        showUsageErr('k3 must contain at least one letter.');

    // Verify that the mode is either 'E' or 'D'
    if (strlen($argv[5]) > 1 || preg_match('/[^EeDd]/', $argv[5]))
        showUsageErr('Mode must be either \'E\' or \'D\'.');
}

// Remove all non English letters and convert to uppercase
function sanitize($text)
{
    return strtoupper(preg_replace('/[^A-Za-z]/', '', $text));
}
?>